### ISSUE TITLE
What about Windows version?

### ISSUE THREAD

**Issue by win32nipuh** [UWSysLab/tapir#1]
Hi, thanks, it is interesting.
Does exist a Windows version?

**Comment by vladwing** [comment]
I would ask if it's possible to compile this project with anything else but clang. Unless it uses LLVM features, it would be nice if we could compile it with other compilers too.

**Comment by iyzhang** [comment]
I believe that we've also compiled it with gcc but I do not think that it would work on Windows. You would have to just edit the Makefile to compile with a different compiler.
