### ISSUE TITLE
go/running the tests

### ISSUE THREAD

**Issue by glycerine** [UWSysLab/tapir#3]
Tapir looks like a super interesting project!

I have two quick questions:

a) is anyone already doing go-bindings or a golang port? 

a) how do I run the tests? gtest-all.cc seems to be missing...
~~~
# on osx 10.11.6 with c++ compiler: Apple LLVM version 8.0.0 (clang-800.0.36.1)
 ~github.com/UWSysLab/tapir (master) $ make test
make test
WARNING: Paranoid mode enabled
make: *** No rule to make target `.obj/gtest/gtest-all.o', needed by `.obj/gtest/gtest_main.a'.  Sto\
p.
~~~

**Comment by iyzhang** [comment]
1. Nope, no one is doing a golang port
2. You need to install gtest, which is the google testing framework
You can get it from here: https://github.com/google/googletest/tree/master/googletest

At some point, we should probably switch over to an easier to use build framework, like CMake, but I'm trying to graduate right now ... :)

**Comment by glycerine** [comment]
1. cool, thanks. I may do a port.
2. gtest was installed. perhaps it isn't getting invoked by the makefile? :|
3. Nice, hope you graduate soon! :)

**Comment by iyzhang** [comment]
2. Ah, the Makefile expects gtest to be at: 
GTEST_DIR := /usr/src/gtest
so set accordingly.

**Comment by glycerine** [comment]
For others reference, I was able to get the tests to build (for googletest downloaded from github.com/google/googletest) by setting this in the top level Makefile:
GTEST_DIR := $(HOME)/go/src/github.com/google/googletest/googletest
